spring.application.name=AiNote
spring.datasource.url=jdbc:postgresql://localhost:5433/notedb
spring.datasource.username=amangeldimadina
spring.datasource.password=mayddee
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
security.jwt.secret=cWUt2AIRI+PRMBEPhDEnMBE/dYc2+4/eiVrVRE6hAVNKrdf9/fqoMaQKvlINcu4fsgMnCKD6BA/1Fm8U6j9zng==
